export const routes = {
  aio: "*",
  "aio/stats": "",
  "aio/users": "",
  "aio/inventory": "",
  "aio/billing": "",
  "aio/settings": "",
  "aio/help": "",
  "aio/orders/acco": "",
  "aio/orders/booking": "",
  "aio/orders/tribes": "",
  "aio/orders/oval": "",
  "aio/orders/katunga": "",
  "aio/orders/karaoke": "",
  "aio/orders/pool": "",
  "aio/orders/laundry": "",
  "aio/orders/lost-key": "",
  "aio/orders/photo-space": "",
  "aio/orders/shisha": "",
  "aio/orders/resv-fb": "",
  "aio/orders/hall": "",
  "aio/orders/bbq": "",
  "aio/orders/cockage": "",
};
